# Generated by Django 4.2.19 on 2026-03-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_skill_level_resumeparsingsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeParsingSession',
        ),
    ]
