# Generated by Django 4.2.19 on 2026-04-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ats_checker', '0001_initial'),
        ('applications', '0003_delete_resumeparsingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ats_analysis_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ats_analysis_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ats_analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ats_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='ats_checker.atsscore'),
        ),
    ]
