# Generated by Django 4.2.19 on 2026-05-10 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0005_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('contribution_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GitHubStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('github_url', models.URLField()),
                ('public_repos', models.IntegerField(default=0)),
                ('total_stars', models.IntegerField(default=0)),
                ('total_forks', models.IntegerField(default=0)),
                ('total_commits', models.IntegerField(default=0)),
                ('total_pull_requests', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('languages', models.JSONField(blank=True, default=dict)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('fetch_status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'GitHub Stats',
                'ordering': ['-last_fetched'],
            },
        ),
        migrations.DeleteModel(
            name='AwardAchievement',
        ),
        migrations.AddField(
            model_name='githubcontribution',
            name='github_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='applications.githubstats'),
        ),
        migrations.AlterUniqueTogether(
            name='githubcontribution',
            unique_together={('github_stats', 'date')},
        ),
    ]
