# Generated by Django 4.2.19 on 2026-05-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_githubcontribution_githubstats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_github_skills_verified',
            field=models.BooleanField(default=False),
        ),
    ]
