# Generated by Django 4.2.19 on 2026-05-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_options_remove_job_recruiter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
    ]
