# Generated by Django 4.2.19 on 2026-05-10 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='target_ats',
            field=models.IntegerField(default=75, help_text='Minimum ATS score required for shortlisting (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
