# Generated by Django 4.2.19 on 2026-03-27 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('raw_text', models.TextField()),
                ('formatted_jd', models.TextField()),
                ('structured_json', models.JSONField(default=dict)),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job Descriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedResumeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('raw_text', models.TextField()),
                ('structured_json', models.JSONField(default=dict)),
                ('extraction_method', models.CharField(default='pdfplumber', max_length=20)),
                ('word_count', models.IntegerField(default=0)),
                ('page_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Extracted Resume Contents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ATSScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField()),
                ('match_percentage', models.FloatField()),
                ('skills_match_score', models.FloatField()),
                ('experience_match_score', models.FloatField()),
                ('education_match_score', models.FloatField()),
                ('keyword_match_score', models.FloatField()),
                ('formatting_score', models.FloatField()),
                ('completeness_score', models.FloatField()),
                ('matching_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('matching_keywords', models.JSONField(default=list)),
                ('missing_keywords', models.JSONField(default=list)),
                ('matching_experience', models.JSONField(default=list)),
                ('missing_experience', models.JSONField(default=list)),
                ('section_suggestions', models.JSONField(default=dict)),
                ('spelling_errors', models.JSONField(default=list)),
                ('grammar_issues', models.JSONField(default=list)),
                ('style_improvements', models.JSONField(default=list)),
                ('formatting_issues', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('detailed_feedback', models.TextField(blank=True)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('improvement_suggestions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats_checker.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ats_checker.extractedresumecontent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ATS Scores',
                'ordering': ['-created_at'],
                'unique_together': {('resume', 'job_description')},
            },
        ),
    ]
