"""Add coding profiles tables

Revision ID: 3041ebc6f699
Revises: ed53ec821f10
Create Date: 2026-03-09 01:13:50.181995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3041ebc6f699'
down_revision: Union[str, Sequence[str], None] = 'ed53ec821f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', name='unique_user_platform')
    )
    op.create_index(op.f('ix_coding_profiles_id'), 'coding_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_coding_profiles_user_id'), 'coding_profiles', ['user_id'], unique=False)
    op.create_table('coding_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('total_solved', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['coding_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_stats_profile_id'), 'coding_stats', ['profile_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coding_stats_profile_id'), table_name='coding_stats')
    op.drop_table('coding_stats')
    op.drop_index(op.f('ix_coding_profiles_user_id'), table_name='coding_profiles')
    op.drop_index(op.f('ix_coding_profiles_id'), table_name='coding_profiles')
    op.drop_table('coding_profiles')
    # ### end Alembic commands ###
