# Generated by Django 4.2.19 on 2026-05-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_address_remove_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('company_employee', 'Company Employee'), ('company_admin', 'Company Admin')], default='job_seeker', max_length=20),
        ),
    ]
