# Generated by Django 4.2.19 on 2026-05-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('user_update', 'User Update'), ('system', 'System Notification'), ('contact', 'Contact'), ('address_added', 'Address Added'), ('address_updated', 'Address Updated'), ('invitation_sent', 'Invitation Sent'), ('invitation_accepted', 'Invitation Accepted'), ('job_application', 'Job Application')], max_length=50),
        ),
    ]
